/**the list of all cards */
export const CARDS=[
    {
        name: "Goblin",
        cost: 1,
        atk: 2,
        hp: 1,
        kind: "minion",
        desc: '',
        id: 1,
        img: 'url(/imgPack/goblin.png)',
        color: 'white',
    },
    {
        name: "Shield",
        cost: 1,
        atk: 1,
        hp: 1,
        kind: "minion",
        desc: 'Deploy: +2 hp',
        onPlay: 'shield',
        id: 2,
        img: 'url(/imgPack/shield.png)',
        color: 'white',
    },
    {
        name: "Thief",
        cost: 3,
        atk: 1,
        hp: 4,
        kind: "minion",
        desc: 'When taking damage: draw a card',
        onDamaged: 'thief',
        id: 3,
        img: 'url(/imgPack/thief.png)',
        color: 'white',
    },
    {
        name: "Boxer",
        cost: 5,
        atk: 1,
        hp: 5,
        kind: "minion",
        desc: 'Before battle: gain 2 atk',
        onAttack: 'boxer',
        onDefense: 'boxer',
        id: 4,
        img: 'url(/imgPack/boxer.png)',
        color: 'white',
    },
    {
        name: "Portal",
        cost: 3,
        atk: 0,
        hp: 1,
        kind: "minion",
        desc: 'Cannot attack and cannot move. On the start of your turn: summon one 2/1 mini goblin on a random adjacent square',
        onTurnBegin: 'portal',
        cannotAttack: true,
        cannotMove: true,
        id: 5,
        img: 'url(/imgPack/portal.png)',
        color: 'white',
    },
    {
        name: "Mouse",
        cost: 2,
        atk: 1,
        hp: 1,
        kind: "minion",
        desc: 'Deploy: summon a mouse on a random adjacent square',
        onPlay: 'mouse',
        id: 6,
        img: 'url(/imgPack/mouse.png)',
        color: 'white',
    },
    {
        name: "Archer Tower",
        cost: 4,
        atk: 3,
        hp: 3,
        kind: "minion",
        desc: "Cannot move. Deal 1 damage to opponent's hero at the start of every turn",
        onEveryTurnBegin: 'archerTower',
        cannotMove: true,
        id: 7,
        img: 'url(/imgPack/archer_tower.png)',
        color: 'white',
    },
    {
        name: "Potion",
        cost: 2,
        kind: "spell",
        desc: "Deal 1 damage to all characters on a square and its adjacent squares.",
        spell: "potion",
        target: "any",
        id: 8,
        img: 'url(/imgPack/potion.png)',
        color: 'white',
    },
    {
        name: "Assassinate",
        cost: 4,
        kind: "spell",
        desc: "Destroy an enemy minion",
        spell: "assassinate",
        target: "enemy minion",
        id: 9,
        img: 'url(/imgPack/assassinate.png)',
        color: 'white',
    },
    {
        name: "Tornado",
        cost: 7,
        kind: "spell",
        desc: "Destroy all unmovable minions. Randomly assign the positions of all minions and heros on the field.",
        spell: "tornado",
        target: "field",
        id: 10,
        img: 'url(/imgPack/tornado.png)',
        color: 'white',
    },
    {
        name: "Assassin",
        cost: 4,
        atk: 3,
        hp: 3,
        kind: "minion",
        desc: "Deploy: add an Assassinate into your hand",
        onPlay: "assassin",
        id: 11,
        img: 'url(/imgPack/assassin.png)',
        color: 'white',
    },
    {
        name: "Mouse Trap",
        cost: 0,
        atk: 0,
        hp: 1,
        kind: "trap",
        desc: "Trigger: deal 1 damage",
        id: 12,
        img: 'url(/imgPack/mouse_trap.png)',
        color: 'green',
        cannotAttack: true,
        cannotMove: true,
        trigger: 'mouseTrap',
    },
    {
        name: "Broken Sword Blade",
        cost: 3,
        atk: 5,
        hp: 1,
        kind: "minion",
        desc: "* Maybe there is a way to fix this? *",
        id: 13,
        img: 'url(/imgPack/broken_sword_blade.png)',
        color: 'white',
    },
    {
        name: "Broken Sword Hilt",
        cost: 3,
        atk: 1,
        hp: 5,
        kind: "minion",
        desc: "* Maybe there is a way to fix this? *",
        id: 14,
        img: 'url(/imgPack/broken_sword_hilt.png)',
        color: 'white',
    },
    {
        name: "Broken Scabbard",
        cost: 3,
        atk: 0,
        hp: 7,
        kind: "minion",
        desc: "* Maybe there is a way to fix this? *",
        id: 15,
        img: 'url(/imgPack/broken_scabbard.png)',
        color: 'white',
    },
    {
        name: "Brave Warrier",
        cost: 3,
        atk: 4,
        hp: 4,
        kind: "minion",
        desc: "* Courage is all she has *",
        id: 16,
        img: 'url(/imgPack/brave_warrier.png)',
        color: 'blue',
    },
    {
        name: "Soul of Soldier",
        cost: 1,
        atk: 2,
        hp: 3,
        kind: "minion",
        desc: "Deploy: Deal 2 damage to your hero",
        onPlay: "soulOfSoldier",
        id: 17,
        img: 'url(/imgPack/soul_of_soldier.png)',
        color: 'white',
    },
    {
        name: "Magic Bunny",
        cost: 2,
        atk: 1,
        hp: 1,
        kind: "minion",
        desc: "On Death: Draw a card",
        onOut: "magicBunny",
        id: 18,
        img: 'url(/imgPack/magic_bunny.png)',
        color: 'green',
    },
    {
        name: "Tiger",
        cost: 8,
        atk: 8,
        hp: 8,
        kind: "minion",
        desc: "",
        id: 19,
        img: 'url(/imgPack/tiger.png)',
        color: 'white',
    },
    {
        name: "Stab",
        cost: 1,
        kind: "spell",
        desc: "Deal 2 damage",
        spell: "stab",
        target: "minion",
        id: 20,
        img: 'url(/imgPack/stab.png)',
        color: 'white',
    },
    {
        name: "Rolling Rock",
        cost: 4,
        kind: "spell",
        desc: "Choose a tile: Deal 2 damage to every unit on the same column",
        spell: "rollingRock",
        target: "any",
        id: 21,
        img: 'url(/imgPack/rolling_rock.png)',
        color: 'white',
    },
    {
        name: "Wrath of Fire",
        cost: 5,
        kind: "spell",
        desc: "Choose a tile: Deal 3 damage to every unit on the same row",
        spell: "wrathOfFire",
        target: "any",
        id: 22,
        img: 'url(/imgPack/wrath_of_fire.png)',
        color: 'white',
    },
    {
        name: "Uplift",
        cost: 3,
        kind: "spell",
        desc: "Grant your minions 1 atk and 1 hp",
        spell: "uplift",
        target: "field",
        id: 23,
        img: 'url(/imgPack/uplift.png)',
        color: 'white',
    },
]